apiVersion: v1
kind: Service
metadata:
  name: ms-ping-svc
  namespace: default
  labels:
    app: ms-ping
    service: ms-ping-svc
spec:
  selector:
    app: ms-ping
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-ping-v1
  namespace: default
  labels:
    app: ms-ping
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-ping
      version: v1
  template:
    metadata:
      labels:
        app: ms-ping
        version: v1
    spec:
      containers:
        - name: ms-ping
          image: lcrbneves/ping:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ms-ping
  namespace: default
spec:
  host: ms-ping-svc
  subsets:
    - name: v1
      labels:
        version: v1